[package]
name = "portscan"
version = "0.1.0"
edition = "2021"
authors = ["Abhinand Rajesh"]
description = "Simple TCP port scanner written in Rust for educational purposes"
repository = "https://github.com/abhinandrajeshfrance/rust_portscan"
readme = "../README.md"

[dependencies]

[[bin]]
name = "portscan"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = true
